resolve #105
metrostroi-repo/MetrostroiAddon pull request #140
Opened 2021-03-04 13:45 UTC by TheFUlDeep

2021-03-14 12:43 UTC, glebqip commented
Немного неверная логика, в строке выше вроде как правильная логика. В текущем варианте опущена необходимость включения галки

2021-03-14 12:43 UTC, glebqip requested changes
Немного неверная логика, в строке выше вроде как правильная логика. В текущем варианте опущена необходимость включения галки

2021-03-15 19:11 UTC, TheFUlDeep commented
> Немного неверная логика, в строке выше вроде как правильная логика. В текущем варианте опущена необходимость включения галки

Не совсем понял. Там же в предыдущей строке (561) уже есть условие на Red, которое работает правильно. И пригласительный пролезает тогда, когда не нужно, именно в строке 564

2021-03-15 19:35 UTC, TheFUlDeep commented
А если так? Два эти условия объединил в одно общее, чтобы было меньше проверок.

2021-03-15 19:40 UTC, glebqip approved these changes
Гуд

2021-03-15 19:40 UTC, merged