#107
metrostroi-repo/MetrostroiAddon pull request #143
Opened 2021-03-16 11:39 UTC by TheFUlDeep

Чтобы постоянно не вызывать функции Vector, Color, Angle, вынес фиксированные значения в отдельные переменные.
Ограничил think функцию, чтобы она выполнялась максимум 20 раз в секунду.
Переместил указание моделей и материалов в shared файл, чтобы их удобнее было менять (для кастомных моделей).
Уменьшил количество конкатенаций, но это не сыграло никакой роли на производительность.
В некоторых местах при повторяющихся вызовах функций вынес результаты в отдельные переменные (как с конкатенацией)
В итоге у меня средний фпс поднялся с 110 до 140.

Скорее всего я что-то пропустил и вообще сделал неправильно. Но у меня просто руки чесались сделать что-нибудь.

2021-03-19 20:02 UTC, glebqip requested changes
Я не знаю всё же, насколько стоит выносить все эти переменные вне. Это выглядит очень нечитаемо в итоге

2021-03-19 20:02 UTC, glebqip commented on lua/entities/gmod_track_signal/shared.lua
> +ENT.ArsBoxModel = "models/metrostroi/signals/mus/ars_box.mdl"
Вынес бы это в ENT.TrafficLightModels лучше, получится более кастомизируемо. Туда же можно разные оффсеты вынести

2021-03-19 20:02 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Color_255_255_255_0 = Color(255,255,255,0)
ColorWhite

2021-03-19 20:02 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Color_0_0_0_255 = Color(0,0,0,255)
ColorBlack

2021-03-19 20:02 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Color_0_100_0_255 = Color(0,100,0,255)
Эти два используются в дебаге, так что наверное это можно не выносить

2021-03-19 20:02 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Angle_0_0_0 = Angle(0,0,0)
AngleZero

2021-03-19 20:02 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Vector_0_0_0 = Vector(0,0,0)
VectorZero

2021-03-19 20:02 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Vector_1_1_1 = Vector(1,1,1)
Всё связанное на умножение с этим можно убрать

2021-03-21 14:53 UTC, TheFUlDeep commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Vector_0_0_0 = Vector(0,0,0)
Глобальной переменной VectorZero не нашел. Зато есть vector_origin. Поменяю на нее

2021-03-21 14:58 UTC, TheFUlDeep commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Color_0_100_0_255 = Color(0,100,0,255)
Мне кажется, что если уж и так дофига всего вынесено, то эти две переменные на читаемость кода никак не повлияют

2021-03-21 15:00 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +local Vector_0_0_0 = Vector(0,0,0)
Я имел ввиду больше назвать её как VectorZero

2021-03-22 08:45 UTC, TheFUlDeep commented
Переместил оффсеты в shared, но я не уверен, что вообще правильно структурировал эту таблицу сделал. И там небольшие беды с именами полей.
Также вспомнил старый баг, когда не работала стрелка (которая как маршрутный указатель). Исправил его и поменял им "буквы" L и R, так как они в противоположные стороны показывали.
Вместо Angle(0,0,0) прописал глобальный vector_origin, аналогично angle_zero и некоторые цвета.

2021-03-22 13:50 UTC, TheFUlDeep commented
Еще по пути #108 вроде как исправил. Возможно надо было отдельную ветку сделать, но я мыслант гигысли.

2021-03-23 23:19 UTC, glebqip commented
Я всё ещё думаю, стоит ли это ПРить. Реально, вынос даёт такой большой прирост? Оно же вроде не делает SetPos каждый тик.
И как с пониженным количеством тиков с анимациями лампочек у светофоров?

2021-03-24 09:09 UTC, TheFUlDeep commented
Вызов функции Vector(0,0,0) в количестве 10000 раз у меня занимает 0,002 секунды. Я считаю, что это ощутимо

Анимация у лампочек в порядке. У автостопа тоже. Конечно, если прям всматриваться внимательно, то видно, что там 20 "фпс". На крайний случай можно до 30ти поднять. Больше, я считаю, точно не нужно.

2021-03-24 10:48 UTC, glebqip commented
У сигналов даже 100 раз вызовов не будет, все функции с векторами вызываются только при появлении в зоне видимости или изменении сигнала однократно. После того, как он заспавнил модельки ничего вызываться не будет, так что я не уверен, что эта оптимизация и вынос тут требуется.
Кстати, по глобальным переменным. Если оптимизируешь так, то обращение к глобальным переменным медленнее, чем к локальным (часто любят делать
`lua
local min = math.min`
И 2мс это не сильно много, но достаточно. 90фпс это 12мс, 60фпс это 20мс, 30фпс уже 34мс

2021-03-24 12:33 UTC, TheFUlDeep commented
> Кстати, по глобальным переменным. Если оптимизируешь так, то обращение к глобальным переменным медленнее, чем к локальным (часто любят делать

Да. Это знаю. Но вызов глобальной переменной все еще быстрее, чем вызов функции Vector. И как раз, чтобы уменьшить количество "выносов", я использовал глобальные.

> У сигналов даже 100 раз вызовов не будет, все функции с векторами должны вызываться только при появлении в зоне видимости или изменении сигнала однократно. После того, как он заспавнил модельки ничего вызываться не будет, так что я не уверен, что эта оптимизация и вынос тут требуется.

Вообще я не обратил внимания, что все эти векторы находятся под условием if not self.ModelsCreated XD. Так что тут, да, оно почти не повлияет на производительность. 
Но если же рассматривать шире, то вынесение из всех think функций даст видимый прирост.

Еще, кстати, надо же учитывать, что у некоторых людей кампуктеры слабые, и там возможно эти приколы дадут какую-то ощутимую разность.


В итоге, надо решить, что нужно изменить.

1. Вернуть векторы, углы и цвета на родину, потому что они вызываются только для спавна моделей (кроме тех, что в shared файле и кроме дебага, потому что в дебаге хук, который очень часто вызывается)
2. Поднять тикрейт финка до 30, чтобы анимации были плавнее
3. ????

2021-03-24 13:03 UTC, glebqip commented
Да и в дебаге векторы вернуть стоит. Дебаг все же не сделан для того, чтобы постоянно работал, и там не важна какая просадка.

Глобальные тоже стоит вернуть думаю, опять же будет более читаемо.

По Shared можешь предлагать, там вроде не такая плохая структура, но я бы вообще большинство кода переписал в cl_init. Сделать бы там всё более гибким и читаемым, и какую нибудь возможность кастомизации прикрутить

2021-03-24 13:37 UTC, TheFUlDeep commented
> По Shared можешь предлагать, там вроде не такая плохая структура, но я бы вообще большинство кода переписал в cl_init.

Я имею ввиду про ту часть, которую я добавил. Там сейчас небольшая каша. 

Логику в cl_init я переписывать скорее всего не буду. Мне страшно вообще смотреть в этот файл)

По остальным моментам сделаю сегодня-завтра.

2021-03-24 15:18 UTC, TheFUlDeep commented
Как-то так. В коммите забыл написать, но глобальные тоже убрал

2021-03-25 11:19 UTC, glebqip approved these changes

2021-03-25 11:28 UTC, glebqip requested changes
Выровняй все отступы в файле, отметил заметные.
В следующий раз проверяй лучше при открытии файла, в метрострое к сожалению сейчас разброс везде по отступам.

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +	local rouid = id and "rou"..id
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +			local idx = add and v..add or v
В файле используются пробелы как отступы, у тебя табуляции (1)
```suggestion
            local idx = add and v..add or v
```

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +				local k_long = k.."_long"
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +		local LampIndicator = self.TrafficLightModels[self.LightType].LampIndicator
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +			local ID_glass = tostring(ID).."_glass"
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +	local IDID2 = ID..ID2
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +        if IsStateAboveZero then
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +		self.Models[3][IDID2]:SetColor(Color(255,255,255,State*255))
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +	local CurTime = CurTime()
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +			for k,v in pairs(self.SpecRouteNumbers) do
(1)

2021-03-25 11:28 UTC, glebqip commented on lua/entities/gmod_track_signal/cl_init.lua
> +												local n = tonumber(sig.Sig[ID2])
(1)

2021-03-25 13:03 UTC, TheFUlDeep commented
Прошелся скриптом, просто заменил все табуляции на пробелы.

2021-03-25 13:06 UTC, TheFUlDeep commented
И еще обнаружил, что у свитчей тоже дебаг не работал. Вроде исправил

2021-03-25 17:13 UTC, glebqip approved these changes

2021-03-25 17:13 UTC, glebqip approved these changes

2021-03-25 17:16 UTC, merged