Fix bugs #91,#79,#38,#72
metrostroi-repo/MetrostroiAddon pull request #216
Opened 2021-05-19 16:35 UTC by ImPerzz

2021-05-21 18:10 UTC, glebqip requested changes
Вопросы по скинам(#91) и по тележке(#38)

2021-05-21 18:10 UTC, glebqip commented on lua/autorun/metrostroi.lua
> +    if CLIENT and category!="cab" and tbl.textures then
Рекомендую у нас использовать ~=, так как большая часть кода написана как ~=. Если очень сложно, можешь использовать "!="

2021-05-21 18:10 UTC, glebqip commented on lua/autorun/metrostroi.lua
> +    if CLIENT and category!="cab" and tbl.textures then
И почему category != "cab"?

2021-05-21 18:10 UTC, glebqip commented on lua/entities/gmod_train_bogey/cl_init.lua
> +    if math.random()>0.5 then self.SoundNames["brake_loop4"] = math.random()>0.5 and self.SoundNames["brake2_loop1"] or self.SoundNames["brake2_loop2"] end
Долго допирал, почему сделано так.
Можно использовать SquealType как на СПБ, вместо переписывания brake_loop4. Кроме того, я немного не понимаю почему тип 4. Дефолтный тип 1

2021-05-21 19:24 UTC, ImPerzz commented on lua/entities/gmod_train_bogey/cl_init.lua
> +    if math.random()>0.5 then self.SoundNames["brake_loop4"] = math.random()>0.5 and self.SoundNames["brake2_loop1"] or self.SoundNames["brake2_loop2"] end
На 717 МСК используется 4 тип судя по скриптам, переделать?

2021-05-21 19:24 UTC, ImPerzz commented on lua/autorun/metrostroi.lua
> +    if CLIENT and category!="cab" and tbl.textures then
~= поменяю, !="cab" потому что это уже текстуры пультов, в принципе можно и пульты чекать

2021-05-21 19:29 UTC, ImPerzz commented on lua/entities/gmod_train_bogey/cl_init.lua
> +    if math.random()>0.5 then self.SoundNames["brake_loop4"] = math.random()>0.5 and self.SoundNames["brake2_loop1"] or self.SoundNames["brake2_loop2"] end
На счёт СПБ, можно тогда поменять SquealType и в коде в принципе больше ничего не менять, в cl_init 292 строка, уже есть условие я так понимаю как раз для СПБ номерных

2021-05-21 19:35 UTC, glebqip commented on lua/autorun/metrostroi.lua
> +    if CLIENT and category!="cab" and tbl.textures then
Лучше тоже чекать

2021-05-21 19:48 UTC, ImPerzz commented on lua/autorun/metrostroi.lua
> +    if CLIENT and category!="cab" and tbl.textures then
Запушил

2021-05-25 22:06 UTC, glebqip requested changes
Попробуй у тележки всё же на SquealType перенести

2021-07-26 06:27 UTC, glebqip requested changes

2021-07-26 06:27 UTC, glebqip commented on lua/entities/gmod_train_bogey/cl_init.lua
> +    if math.random()>0.5 then self.SoundNames["brake_loop4"] = math.random()>0.5 and self.SoundNames["brake2_loop1"] or self.SoundNames["brake2_loop2"] end
Вот это стоит убрать, не нравится мне такой хардкод

2021-07-26 21:25 UTC, ImPerzz commented on lua/entities/gmod_train_bogey/cl_init.lua
> +    if math.random()>0.5 then self.SoundNames["brake_loop4"] = math.random()>0.5 and self.SoundNames["brake2_loop1"] or self.SoundNames["brake2_loop2"] end
Забыл убрать, действительно

2021-07-27 10:15 UTC, glebqip approved these changes

2021-07-27 10:16 UTC, merged