#29
metrostroi-repo/MetrostroiAddon pull request #265
Opened 2021-07-09 00:41 UTC by kosmik641

resolve #29

2021-07-09 02:27 UTC, glebqip requested changes
Вынести на сервер бы рандом появления, чтобы искра была у всех одинаково

2021-07-09 02:27 UTC, glebqip commented on lua/entities/gmod_train_bogey/cl_init.lua
> +    if math.random() > probability then
Вынести на сервер бы рандом появления, чтобы искра была у всех одинаково

2021-07-09 02:29 UTC, glebqip commented
А ещё если есть на клиенте PantLPos и т.п., то можно передавать вместо вектора ИД или булеан (лучше ИД)

2021-07-09 02:31 UTC, kosmik641 commented
> А ещё если есть на клиенте PantLPos и т.п., то можно передавать вместо вектора ИД или булеан (лучше ИД)

А вот нету, пожтому вектор и передаю

2021-07-09 21:04 UTC, glebqip commented
Гуд! Ещё бы попросил перенести звук на клиент вместе с искрой, раз уж такая пьянка

2021-07-09 21:06 UTC, kosmik641 commented
> Гуд! Ещё бы попросил перенести звук на клиент вместе с искрой, раз уж такая пьянка

Звук прижатия токоприемника?

2021-07-10 14:49 UTC, glebqip commented
> Звук прижатия токоприемника?

Угу

2021-07-12 16:46 UTC, glebqip approved these changes

2021-07-12 16:46 UTC, merged