#310
metrostroi-repo/MetrostroiAddon pull request #312
Opened 2021-07-28 23:24 UTC by Hellss

resolve #310

2021-07-29 04:35 UTC, alexandr-sizov commented
Что это. pass occup галка это вообще другое, САО задается двойкой в АРСCodes

2021-07-29 08:02 UTC, Hellss commented
Так ты второй коммит смотри 
Первый не надо

2021-07-29 08:05 UTC, alexandr-sizov commented
> Так ты второй коммит смотри 
> Первый не надо 

Почему не надо? Он же тоже смержится

2021-07-29 08:07 UTC, alexandr-sizov commented
И я не понял что произошло тут:<!-- Error while uploading Screenshot_2021-07-29-11-06-41-962_com.github.android.jpg -->

2021-07-29 08:09 UTC, alexandr-sizov commented
+ я считаю что твое сокращение passoc надо заменить на понятное, что то вроде AbsStop

2021-07-29 08:19 UTC, Hellss commented
так первый я не так сначала понял поэтому во втором и третьем все сделал

2021-07-29 08:31 UTC, Hellss commented
> И я не понял что произошло в файле signaling.lua

singal в signal переименовал

2021-07-29 08:41 UTC, alexandr-sizov commented
Не вижу сброса отключения САО при смене САО на разрешающую частоту.

2021-07-29 09:09 UTC, Hellss commented
Так арскоды может только либо маршрут либо занятость изменить
Это вроде сделал

2021-07-29 09:12 UTC, alexandr-sizov commented
> Так арскоды может только либо маршрут либо занятость изменить
> Это сделано

Пример - прописано в кодах 222224, freebs = 2, так вот когда freebs станет 5 и больше, то должно появится 40, по твоему коду вроде остается ОЧ.

2021-07-29 09:21 UTC, Hellss commented
добавил проверку на арскоды

2021-07-29 09:22 UTC, Hellss commented
табуляция съехала, не знаю почему 
замена таба =  4 пробела стоит

2021-07-29 09:24 UTC, alexandr-sizov commented
> добавил проверку на арс коды

Надо добавлять проверку не на разрешающие частоты, а на любые отличные от САО

2021-07-29 09:32 UTC, alexandr-sizov commented
>  Так же я считаю что твое сокращение passoc надо заменить на понятное, что то вроде AbsStop. В том числе в подсказках ulx. "Enable/disable absolutely stop signal"

И что с этим? Хотя бы подсказки ulx

2021-07-29 10:03 UTC, Hellss commented
все вроде сделал
табы пофиксил и переименовал подсказки

2021-07-31 16:39 UTC, glebqip requested changes

2021-07-31 16:39 UTC, glebqip commented on lua/ulx/modules/sh/metrostroi.lua
> +senao:help( "Enable absolutely stop signal" )
Enable absolute stop signal

2021-07-31 16:39 UTC, glebqip commented on lua/ulx/modules/sh/metrostroi.lua
> +sdisao:help( "Disable absolutely stop signal" )
Disable absolute stop signal

2021-07-31 16:39 UTC, glebqip commented on lua/entities/gmod_track_signal/init.lua
> +                if sig.ARSSpeedLimit == 2 then sig.AODisabled = true end
Табуляция (в этом файле табами)

2021-07-31 16:39 UTC, glebqip commented on lua/entities/gmod_track_signal/init.lua
> +        self.AODisabled = false
Табуляция (в этом файле табами)

2021-07-31 16:39 UTC, glebqip commented on lua/entities/gmod_track_signal/init.lua
> +            self.ARSSpeedLimit = tonumber(ARSCodes[math.min(#ARSCodes, self.FreeBS+1)]) or 0
Табуляция

2021-08-01 21:28 UTC, glebqip requested changes
![image](https://user-images.githubusercontent.com/6125008/127785759-a3df9dbc-9838-4f89-ad55-1f9e41f664c1.png)
![image](https://user-images.githubusercontent.com/6125008/127785762-0d9e4aa0-24d8-466c-b5f2-b13cad4cdc55.png)
Пожалуйста, почини табуляцию. Она во всём файле табами, а не проблелами, зачем ты сделал ещё хуже?

2021-08-01 21:28 UTC, glebqip commented on lua/ulx/modules/sh/metrostroi.lua
> +senao:addParam{ type=ULib.cmds.StringArg, hint="Signal or route name", ULib.cmds.takeRestOfLine }
Тут кстати описание тоже неверно, у нас же route name не сработает

2021-08-01 21:28 UTC, glebqip commented on lua/entities/gmod_track_signal/init.lua
> +                if sig.ARSSpeedLimit == 2 then sig.AODisabled = true end
Всё ещё не пофикшено

2021-08-01 21:28 UTC, glebqip commented on lua/entities/gmod_track_signal/init.lua
> +        self.AODisabled = false
Всё ещё не пофикшено

2021-08-01 21:28 UTC, glebqip commented on lua/entities/gmod_track_signal/init.lua
> +            self.ARSSpeedLimit = tonumber(ARSCodes[math.min(#ARSCodes, self.FreeBS+1)]) or 0
Всё ещё не пофикшено

2021-08-04 08:58 UTC, glebqip approved these changes

2021-08-04 08:58 UTC, merged