#297
metrostroi-repo/MetrostroiAddon pull request #338
Opened 2021-08-04 04:55 UTC by kosmik641

resolve #297

2021-08-04 08:55 UTC, glebqip requested changes

2021-08-04 08:55 UTC, glebqip commented on lua/metrostroi/systems/sys_81_722_mfdu.lua
> +                    if self.Selected == 1 then self.RouteN = self.RouteN or self.RouteNumber        self.RouteNumber = self.RouteN end
Очень странный код. Не логичнее ли сделать:
```lua
self.RouteNumber = self.RouteN or self.RouteNumber
```
или вообще
```lua
if self.RouteN and self.Selected == 1 then self.RouteNumber == self.RouteN end
```

2021-08-04 08:56 UTC, glebqip commented on lua/metrostroi/systems/sys_81_722_mfdu.lua
> +                    if self.Selected == 1 then self.RouteN = self.RouteN or self.RouteNumber        self.RouteNumber = self.RouteN end
Это касается всех этих трёх строк

2021-08-04 10:01 UTC, kosmik641 commented on lua/metrostroi/systems/sys_81_722_mfdu.lua
> +                    if self.Selected == 1 then self.RouteN = self.RouteN or self.RouteNumber        self.RouteNumber = self.RouteN end
Если посмотришь чуть ниже, в SetNW2 передается self.RouteN (как раз то, что показывается, что ты вводишь), поэтому такой код

2021-08-04 10:03 UTC, kosmik641 commented on lua/metrostroi/systems/sys_81_722_mfdu.lua
> +                    if self.Selected == 1 then self.RouteN = self.RouteN or self.RouteNumber        self.RouteNumber = self.RouteN end
Либо вообще отказаться от self.RouteN (и ему подобных) и менять значение "на ходу"

2021-12-28 15:03 UTC, HellReach approved these changes

2021-12-28 15:05 UTC, kosmik641 reviewed
С Глебом обсудили, всё нормально

2021-12-28 15:06 UTC, merged