Fixed battery charging, position of voltmeter
metrostroi-repo/MetrostroiAddon pull request #97
Opened 2021-01-06 20:32 UTC by toxin1pilot

#95

2021-01-07 18:40 UTC, glebqip commented
Можешь табуляции на пробелы заменить?

2021-01-07 18:42 UTC, glebqip requested changes

2021-01-07 18:42 UTC, glebqip commented on lua/entities/gmod_subway_ezh3/cl_init.lua
> +	self:Animate("volt1",self:GetPackedRatio("BatteryVoltage"),0.613,0.455,72,2)
Замени на пробелы

2021-01-07 18:42 UTC, glebqip commented on lua/metrostroi/systems/sys_81_508t_electric.lua
> +	Train.Battery:TriggerInput("Charge", Train.VB.Value*Panel.MainLights1)
Замени на пробелы

2021-01-07 18:42 UTC, glebqip commented on lua/metrostroi/systems/sys_81_710_electric.lua
> +	Train.Battery:TriggerInput("Charge", Train.VB.Value*Panel.MainLights1)
Замени на пробелы

2021-01-07 22:49 UTC, toxin1pilot commented on lua/entities/gmod_subway_ezh3/cl_init.lua
> +	self:Animate("volt1",self:GetPackedRatio("BatteryVoltage"),0.613,0.455,72,2)
Можно для глупых, я забыл убрать строку старую, исправлю, а к остальным файлам в плане заменить на пробелы, что именно?*

2021-01-08 13:33 UTC, glebqip commented on lua/entities/gmod_subway_ezh3/cl_init.lua
> +	self:Animate("volt1",self:GetPackedRatio("BatteryVoltage"),0.613,0.455,72,2)
Весь код использует пробелы в отступах, а твой табуляции. В редакторе можно поменять на Use spaces(вообще автоматически должен был определить).

2021-01-08 22:59 UTC, cyber-dream commented
Какой прогресс по pr @toxin1pilot

2021-01-11 14:32 UTC, glebqip approved these changes

2021-01-11 14:32 UTC, merged